apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::324573547520:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::324573547520:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-N4QYS13OMT24
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-08T21:23:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-06-08T21:23:00Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-06-08T21:38:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4531"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fba56783-7445-4e4e-8b26-7294c1cd7a0d
